### ISSUE TITLE
No module named 'arxiv''

### ISSUE THREAD

**Issue by Ryan147** [rmusser01/tldw#327]
Installed tldw for windows and when I want to run it I get the following error message:

Database path: Databases/media_summary.db
Backup directory: Y:\tldw\tldw\./tldw_DB_Backups/
Author column already exists in Prompts table.
Database path: Y:\tldw\tldw\Databases\media_summary.db
Database path: Y:\tldw\tldw\Databases\media_summary.db
Traceback (most recent call last):
  File "Y:\tldw\tldw\summarize.py", line 18, in <module>
    from App_Function_Libraries.Gradio_Related import launch_ui
  File "Y:\tldw\tldw\App_Function_Libraries\Gradio_Related.py", line 18, in <module>
    from App_Function_Libraries.Gradio_UI.Arxiv_tab import create_arxiv_tab
  File "Y:\tldw\tldw\App_Function_Libraries\Gradio_UI\Arxiv_tab.py", line 12, in <module>
    from App_Function_Libraries.Third_Party.Arxiv import convert_xml_to_markdown, fetch_arxiv_xml, parse_arxiv_feed, \
  File "Y:\tldw\tldw\App_Function_Libraries\Third_Party\Arxiv.py", line 5, in <module>
    import arxiv
ModuleNotFoundError: No module named 'arxiv'

But arxiv is installed.

**Comment by rmusser01** [comment]
Thank you for opening an issue, sorry about that. I just pushed an update that updated requirements.txt to include the `arxiv` package.

If you'd like to resolve the issue, from your virtual env, run the command `pip install arxiv`, which will install the missing module.

Otherwise, you can re-install using the install script if you're uncomfortable/not familiar with pip/pyvenv.

**Comment by Ryan147** [comment]
Thank you for fixing it!

I re-installed and it worked. Thanks a bunch for TLDW :)
